# Copyright 2021 ETH Zurich and the NestForge authors.
# SPDX-License-Identifier: GPL-3.0-or-later
"""Kernel optimization: schedule one kernel, give DaCe's program one C entry, build and validate ``lib<kernel>.a``."""
from __future__ import annotations

import copy
import dataclasses
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

import dace
from dace.transformation.passes.canonicalize.finalize import finalize_for_target
from dace.transformation.passes.vectorization import VectorizeCPUMultiDim
from dace.transformation.passes.vectorization.config import VectorizeConfig

from nestforge.build.arena import call_native, diff_stats, dtype_floor, make_inputs, rung_atol, run_oracle
from nestforge.build.isolation import run_isolated
from nestforge.build.sdfg import BuildOptions, GeneratedProgram, build_archive, generate_program
from nestforge.build.toolchain import parse_params, raw_signature, signature, split_params
from nestforge.corpus.translate import Prepared
from nestforge.ir.extract import Boundary
from nestforge.ir.libnode import ExternalCall
from nestforge.phases.normalize import Targets

#: 8 lanes suit AVX2 and satisfy AVX-512's multiple-of-8 tile width.
VECTOR_WIDTHS: Tuple[int, ...] = (8, )

#: By-value types ``ExternalCall``'s prototype spells ``double``; every other symbol is ``int64_t``.
FLOAT_TYPES = ("double", "float")

WRAPPER = """// Generated by nestforge.phases.kernel: the one C entry of lib{kernel}.a.
#include <cstdint>

struct {name}_state_t;

extern "C" {{
{name}_state_t *__dace_init_{name}({init_decls});
void __program_{name}({program_decls});
int __dace_exit_{name}({name}_state_t *__state);

void {kernel}({entry_decls}) {{
    {name}_state_t *handle = __dace_init_{name}({init_args});
    __program_{name}({program_args});
    static_cast<void>(__dace_exit_{name}(handle));
}}
}}
"""


@dataclass(slots=True)
class KernelSource:
    """DaCe's generated program for one kernel plus the wrapper TU defining its C entry."""
    name: str
    program: GeneratedProgram
    wrapper: Path
    abi_order: List[str]
    boundary: Boundary

    @property
    def symbol(self) -> str:
        return self.name


@dataclass(slots=True)
class KernelVerdict:
    """A build compared to the NumPy oracle and timed; ``ok`` gates at ``fp_mode``."""
    fp_mode: str
    maxdiff: float
    md_rel: float
    dtype_floor: float
    time_us: float
    error: str = ""

    @property
    def ok(self) -> bool:
        return not self.error and self.md_rel <= rung_atol(self.fp_mode, self.dtype_floor)


def failed_verdict(fp_mode: str, error: str) -> KernelVerdict:
    return KernelVerdict(fp_mode, float("inf"), float("inf"), 0.0, float("inf"), error)


def at_rung(verdict: KernelVerdict, fp_mode: str) -> KernelVerdict:
    """The same measurement gated at another FP rung."""
    return dataclasses.replace(verdict, fp_mode=fp_mode)


def split_decl(decl: str) -> Tuple[str, str]:
    """``(type, name)`` of one C parameter declaration."""
    text = " ".join(decl.split())
    name = re.split(r"[\s*]+", text)[-1]
    return text[:text.rfind(name)].strip(), name


def entry_decl(ctype: str, name: str, data: bool) -> Tuple[str, str]:
    """The entry's declaration of one ``__program`` parameter and the forwarded argument. ``ExternalCall``
    passes data by pointer and symbols as ``int64_t``/``double``, so those are converted, not re-declared."""
    if "*" in ctype:
        return f"{ctype} {name}", name
    if data:
        return f"const {ctype}* {name}", f"*{name}"
    wide = "double" if ctype.replace("const", "").strip() in FLOAT_TYPES else "int64_t"
    return f"{wide} {name}", f"static_cast<{ctype}>({name})"


def wrapper_source(kernel: str, program: GeneratedProgram, boundary: Boundary) -> Tuple[str, List[str]]:
    """``(wrapper TU defining extern "C" <kernel>, its parameter order)``; the order is ``__program``'s."""
    name = program.name
    program_text = signature(program.source, f"__program_{name}")
    init_text = signature(program.source, f"__dace_init_{name}")
    data = {*boundary.inputs, *boundary.outputs}
    params = [split_decl(p) for p in split_params(program_text)[1:]]  # [0] is the state handle
    forwarded = [entry_decl(ctype, pname, pname in data) for ctype, pname in params]
    init_args = [f"static_cast<{ctype}>({pname})" for ctype, pname in map(split_decl, split_params(init_text))]
    text = WRAPPER.format(kernel=kernel,
                          name=name,
                          init_decls=init_text.strip(),
                          program_decls=program_text.strip(),
                          entry_decls=", ".join(decl for decl, _ in forwarded),
                          init_args=", ".join(init_args),
                          program_args=", ".join(["handle", *[arg for _, arg in forwarded]]))
    return text, [pname for _, pname in params]


def default_schedule(boundary: Boundary, targets: Targets) -> dace.SDFG:
    """A copy of the kernel with DaCe's default CPU vectorizer and ``finalize_for_target`` applied."""
    if targets.gpu:
        raise NotImplementedError("GPU kernels arrive with phase 2.5")
    sdfg = copy.deepcopy(boundary.standalone_sdfg)
    VectorizeCPUMultiDim(VectorizeConfig(widths=VECTOR_WIDTHS, expand_tile_nodes=True)).apply_pass(sdfg, {})
    return finalize_for_target(sdfg, "cpu")


def schedule_kernel(ext: ExternalCall, boundary: Boundary, targets: Targets, out_dir: Path) -> KernelSource:
    """:func:`default_schedule`, DaCe codegen into ``out_dir``, and the wrapper TU for ``ext``'s symbol."""
    program = generate_program(default_schedule(boundary, targets), out_dir)
    text, abi_order = wrapper_source(ext.name, program, boundary)
    wrapper = program.frame.with_name(f"{ext.name}_entry.cpp")
    wrapper.write_text(text)
    return KernelSource(ext.name, program, wrapper, abi_order, boundary)


def build_kernel_library(src: KernelSource, compiler: str, flags: Optional[List[str]], out_dir: Path) -> Path:
    """Build ``<out_dir>/lib<kernel>.a`` from frame and wrapper, plus its shared twin for validation."""
    archive = out_dir / f"lib{src.name}.a"
    opts = BuildOptions(compiler=compiler, flags=flags, link_external=True)
    build_archive([src.program.frame, src.wrapper], src.program.folder, archive, archive.with_suffix(".so"), opts)
    return archive


def use_kernel_library(ext: ExternalCall, lib_path: Path, symbol: str, abi_order: List[str]) -> None:
    """Point ``ext`` at a built library and select the extern-call expansion."""
    ext.lib_path, ext.symbol, ext.abi_order = str(lib_path), symbol, list(abi_order)
    ext.implementation = "ExternCall"


def measure_kernel(archive: Path, src: KernelSource, inputs: Dict[str, np.ndarray], oracle: Dict[str, np.ndarray],
                   sizes: Dict[str, int], reps: int, fp_mode: str) -> KernelVerdict:
    """Call the twin's C entry in a forked child: one run compared to ``oracle``, then ``reps`` timed runs.
    A crash or timeout comes back as a verdict with ``error`` set."""
    argtypes = [p.ctype for p in parse_params(raw_signature(src.wrapper.read_text(), src.symbol))]
    shared = archive.with_suffix(".so")

    def work() -> Dict[str, float]:
        outs, us = call_native(shared, src.symbol, src.abi_order, argtypes, src.boundary, inputs, sizes, reps)
        assert outs is not None, "call_native snapshots outputs unless told not to"
        md, md_rel = diff_stats(oracle, outs)
        return {"maxdiff": md, "md_rel": md_rel, "dtype_floor": dtype_floor(outs), "time_us": us}

    res = run_isolated(work)
    if "error" in res:
        return failed_verdict(fp_mode, str(res["error"]))
    return KernelVerdict(fp_mode, float(res["maxdiff"]), float(res["md_rel"]), float(res["dtype_floor"]),
                         float(res["time_us"]))


def validate_kernel(archive: Path,
                    src: KernelSource,
                    prep: Prepared,
                    sizes: Dict[str, int],
                    reps: int = 10,
                    fp_mode: str = "strict-ieee") -> KernelVerdict:
    """:func:`measure_kernel` on seeded inputs against the kernel's NumPy oracle."""
    inputs = make_inputs(src.boundary, sizes)
    oracle = run_oracle(prep, src.boundary, inputs, sizes)
    return measure_kernel(archive, src, inputs, oracle, sizes, reps, fp_mode)
